### ISSUE TITLE
[Bug] Page with Internal Server Error

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#155]
This page has a server error: https://oldinsurancemaps.net/resource/8032

**Comment by mradamcox** [comment]
As far as I can tell, this was due to a mix up of undone sessions (or something). The resource question was a layer created from a sheet that should have been split but wasn't. Perhaps undoing the georeferencing didn't properly delete this layer?

It's sorted now, the layer in question has been removed and the original document had already been re-split into two, so these pieces can now be georeferenced like normal.

Also took the opportunity to update the 500 and 404 error templates.
