### ISSUE TITLE
Multimask interface is greyed out for one volume

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#168]
I may have totally [broken the mutlimask for this volume](https://oldinsurancemaps.net/loc/sanborn09064_020/#multimask). I had to do some weird shenanigans to try to work around [a small section of a map that had an out-of-scale section](https://github.com/mradamcox/ohmg/discussions/154#discussioncomment-8309977). Now the multimask interface is frozen just for this page… but it works on other volumes. If the solution is for you to just nuke all the masks on this volume, then go for it. It needed to be significantly reworked anyway. This is also the volume that has the [undo preparation issue](https://github.com/mradamcox/ohmg/issues/167). Thoughts on what’s happening?

![image](https://github.com/mradamcox/ohmg/assets/136510277/300584f1-3ac2-4097-bff3-495546ccf52a)

**Comment by mradamcox** [comment]
I have a feeling this could be caused by another issue someone found that I haven't put into a ticket yet: If you trim a layer, and _then_ classify it as a key map, that breaks things. The way to fix this is re-classify it to Main Content and then delete its mask from the MultiMask, save mask, and then reclassify as key map. This is all just due to the way the multimask is handled at the item (volume) level... ultimately any group of layers (key map, main content, etc.) should be able to have their own mask, but for now it's just the main content.

**Comment by rchampine** [comment]
Interesting... I tried that for this volume but it didn't have any effect. My hunch is that it's related to either https://oldinsurancemaps.net/resource/7582 or https://oldinsurancemaps.net/resource/7582 (and/or its children), both are misbehaving.

**Comment by mradamcox** [comment]
Ok, I dealt with 7582, but what was the other you meant to mention?

**Comment by rchampine** [comment]
Whoops — this one: https://oldinsurancemaps.net/resource/7512

**Comment by mradamcox** [comment]
It may have been a combo of these things, once I fixed the multiple prep sessions I was able to delete the masks for all layers, now you'll just have to start over with the masks, everything else should be ok. Sorry about that! Let's leave this ticket open until I can make a better one about multimask management.

**Comment by rchampine** [comment]
All good! Thanks for solving. This volume has been a tricky one.
