### ISSUE TITLE
[Bug] Map viewer does not maximize in Safari

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/ohmg#58]
**Describe the problem**
The maximize button in the volume map viewer doesn't seem to do anything in Safari 15.3. When clicked in Chrome 98.0.4758.109 and Firefox 97.0.2, the map does go full screen.

**Environment info:**
 - Device: M1 Mac Mini
 - Operating System: MacOS Monterey
 - Browser: Safari 15.3

**Comment by mradamcox** [comment]
Unfortunately, seems like fullscreen is trickier with Safari, especially on iPhone (which is where I first saw the issue just yesterday). Here are some reference links for when I can look into this further, because

https://www.w3schools.com/howto/howto_js_fullscreen.asp
https://stackoverflow.com/questions/15509389/is-there-a-way-to-tell-whether-safari-is-fullscreen-e-g-document-fullscreenel
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide

**Comment by mradamcox** [comment]
Given the screenshots in #72, it seems like things have improved a bit, but I'm going to keep this ticket open and close that one, so progress on this can stay in one place.

**Comment by mradamcox** [comment]
Closing this now. I've remove all native fullscreen controls in favor of a new "fake fullscreen" option that maximizes content within the page frame.
